# Generated by Django 6.0.1 on 2026-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('album_art', models.URLField(blank=True)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
    ]
