# Generated by Django 6.0.1 on 2026-04-10 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('album_art', models.URLField(blank=True)),
                ('artist', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('name', 'deezer_id', 'album_art', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='UserTopSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_top_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
