# Generated by Django 6.0.1 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
