# Generated by Django 6.0.1 on 2026-03-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'deezer_id', 'album_art', 'artist')},
        ),
    ]
